- aggiunta documentazione relativa alla funzione Aziende dell'applicazione PCTO
ittagnelli/SARP pull request #537
Opened 2024-04-12 21:04 UTC by Romano-Gabriele

2024-04-13 10:04 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +La sezione *PCTO*, indirizzata principalmente agli amministratori di SARP e permette la gestione completa dei PCTO.
la sezione PCTO è principalmente dedicata a Tutor Scolastici, tutor aziendali e studenti

2024-04-13 10:05 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +1. **Aziende**: permette di creare a sistema una nuova azienda (o convenzione). Sono richiesti (anche se opzionali) tutti i principali dati necessari per stipulare la convenzione con una data azienda
tutor scolastici

2024-04-13 10:05 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +2. **Stage**: Permette di creare uno o più *stage** (PCTO) per ogni azienda presente a sistema. Informazioni fondamentali sono il tutor aziendale e quello scolastico. Gli stage possono essere manipol
*stage** non è valid oin markdow

2024-04-13 10:05 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +- **NO.**: numero dell'azienda
no convenzione

2024-04-13 10:05 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +- **ISTITUTO**: indica per quale istituto è indirizzato il pcto
la convenzione

2024-04-13 20:09 UTC, Romano-Gabriele commented
ho corretto tutto come da lei richiesto

2024-04-14 08:18 UTC, profmancusoa commented
bene ottimo lavoro, vai avanti così

2024-04-14 12:04 UTC, Romano-Gabriele commented
ho eseguito un nuovo commit con la documentazione relativa agli stage

2024-04-14 13:03 UTC, Romano-Gabriele commented
ho eseguito un nuovo commit con la documentazione relativa alle presenze

2024-04-14 16:26 UTC, Romano-Gabriele commented
ho eseguito un nuovo commit con la documentazione relativa alla valutazione degli studenti

2024-04-15 16:52 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +  - **A.S.**: anno scolastico di inserimento dello stage nel sistema
anno scolastico di svolgimento dello stage

2024-04-15 16:52 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +  - **ORE**: indica la durata dello stage (in ore)
durata prevista

2024-04-15 16:53 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +  - **INIZIO**: indica la data di inizio dello stage
AS, tutor, ore inizio perchè sono indentante.
da riportare indietro di un livello

2024-04-15 16:54 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +
aggiungerei la spiegazione del campo Orario Accesso che ha un formato particolare da rispettare

2024-04-15 16:55 UTC, profmancusoa requested changes
ottimo lavoro

2024-04-15 21:38 UTC, Romano-Gabriele commented
ho eseguito un nuovo commit con le correzioni da lei richieste, mi faccia sapere se la spiegazione del formato del campo "Opzioni Accesso" può andare bene

2024-04-16 17:17 UTC, profmancusoa commented on server_static/documentazione/pcto.md
> +Nel campo *Orario Accesso* il formato da rispettare è 00:00-00:00.
non è corretto. c'e' una parte opzionale. devi spiegare come funziona

2024-04-23 21:10 UTC, Romano-Gabriele commented
ho eseguito un nuovo commit con la documentazione relativa alla verifica dello stato e l'aggiunta da lei richiesta nella documentazione relativa agli stage

2024-05-05 08:55 UTC, profmancusoa approved these changes
Ottimo lavoro! bravo!

2024-05-05 08:56 UTC, merged