Issue 533
ittagnelli/SARP pull request #550
Opened 2024-05-09 21:27 UTC by riccardo-girone

creata documentazione per programmazione annuale

2024-05-09 21:35 UTC, riccardo-girone commented
risolto i problemi di merge conflict

2024-05-10 12:42 UTC, profmancusoa requested changes
non sono accettate modifiche al file +layout.svelte, quindi rimuovere dalla pr

2024-05-10 12:42 UTC, profmancusoa requested changes
non sono accettate modifiche al file package-lock.json quindi rimuovere da PR

2024-05-10 12:43 UTC, profmancusoa requested changes
i  nomi delle imamgini devono avere un minimo di senso. prova1 proiva2 non accettabile

2024-05-10 12:47 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +## TEMPLATE DOCENTE
aggiungere introduzione generale su quali sono gli obiettivi dell'applicazione programmazione annuale

2024-05-10 12:48 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +La schermata template docente della sezione *PROGRAMMAZIONE ANNUALE* mostra una tabella con varie colonne contenenti la lista di tutte le programmazioni fatte fino a quel momento. In alto a destra vi
modificare il nome del botton con quello reale dell'applicazione

2024-05-10 12:48 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +## TEMPLATE DOCENTE
spiegare cos'e' un template e come si usa

2024-05-10 12:49 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +- **LIBRO DI TESTO**: nome del libro di testo, bisogna aggiungere tutti i parametri richiesti.
spiegare bene il formato del libro di testo
spiegare che si possono aggiungere più di un linro di testo

2024-05-10 12:50 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +- **MATERIA**: nome della materia
spiegare che un template è associato ad una sola materia di insegnamento

2024-05-10 12:50 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +## PROGRAMMAZIONE DOCENTE
spiegare cosa vede un docente e cioè che vede solo le materie per le classi in cui insegna

2024-05-10 12:51 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +![tabella_programmazioneannuale](/img/documentazione/programmazione-annuale/prova3.png)
l'immagine NON va bene siccome tagli la parte delle azioni

2024-05-10 12:52 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +
aggiungere immagine che fa vedere il form di compilazione della programmazione e spiegare le varie opzioni.
come usare e applicare un template.

spiegare che dopo che un template è stato applicato si può ulteriormente modificare la programmazione

2024-05-10 12:52 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +## PROGRAMMAZIONE CLASSE
questa la vede solo la segreteria e ADMIN
spiegare quando compaiono le due stampanti  e il concetto di programmazione di inizio e di fine anno

2024-05-11 16:32 UTC, profmancusoa commented on server_static/documentazione/programmazione_annuale.md
> +## PROGRAMMAZIONE ANNUALE
chiamalo INTRODUZIONE

2024-05-11 16:44 UTC, profmancusoa approved these changes

2024-05-11 16:45 UTC, merged